# Site
name: "Together Institute"
description: "Together Institute is an organization focused on helping older adults ageg in place."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
disqus: "together-institute"
email: "wowthemesnet@gmail.com"
mailchimp-list: "http://eepurl.com/gGvWzn"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  Kevin:
    name: Kevin
    site: https://www.wowthemes.net
    avatar: /assets/images/avatar1.jpg
    bio: "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
    email: wowthemesnet@gmail.com
    twitter: https://twitter.com/wowthemesnet

  Zack:
    name: Zack
    site: https://www.wowthemes.net
    avatar: /assets/images/avatar2.jpg
    bio: "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
