# Site
name: "Together Institute"
description: "Together Institute is an organization focused on helping older adults ageg in place."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
disqus: "together-institute"
email: "wowthemesnet@gmail.com"
mailchimp-list: "http://eepurl.com/gGvWzn"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  Kevin:
    name: Kevin
    avatar: assets/images/avatar1.jpg
    bio: "Hi, I'm Kevin. I've spent my career working in technology and am dedicated to solving problems for older adults. I'm a mentor at the YMCA Reach and Rise Program, volunteer at the Institute for Aging, and hold an economics degree from University of California, San Diego."

  Zack:
    name: Zack
    avatar: assets/images/avatar2.jpg
    bio: "Hi, I'm Zack! I've worked with older adults for the past 9 years as an activities assistant at a nursing home, community organizer of intergenerational events for non-profits to most recently working at Umbrella: a service that connects older adults with local handy people in their communities."

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: kevin
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
